export {default as Home} from './Home'
export {default as Signin} from './Signin'
export {default as Register} from './Register'
export {default as Signout} from './Signout'
export {default as Dashboard} from './Dashboard'
export {default as Adminlogin} from './Adminlogin'